const charNames = [
    'Mario',
    'Donkey Kong',
    'Link',
    'Samus',
    'Dark Samus',
    'Yoshi',
    'Kirby',
    'Fox',
    'Pikachu',
    'Luigi',
    'Ness',
    'Captain Falcon',
    'Jigglypuff',
    'Peach',
    'Daisy',
    'Bowser',
    'Ice Climbers',
    'Sheik',
    'Zelda',
    'Dr. Mario',
    'Pichu',
    'Falco',
    'Marth',
    'Lucina',
    'Young Link',
    'Ganondorf',
    'Mewtwo',
    'Roy',
    'Chrom',
    'Mr. Game and Watch',
    'Meta Knight',
    'Pit',
    'Dark Pit',
    'Zero Suit Samus',
    'Wario',
    'Snake',
    'Ike',
    'Pokemon Trainer',
    'Diddy Kong',
    'Lucas',
    'Sonic',
    'King Dedede',
    'Olimar',
    'Lucario',
    'R.O.B.',
    'Toon Link',
    'Wolf',
    'Villager',
    'Mega Man',
    'Wii Fit Trainer',
    'Rosalina & Luma',
    'Little Mac',
    'Greninja',
    'Palutena',
    'Pac-Man',
    'Robin',
    'Shulk',
    'Bowser Jr.',
    'Duck Hunt',
    'Ryu',
    'Ken',
    'Cloud',
    'Corrin',
    'Bayonetta',
    'Inkling',
    'Ridley',
    'Simon',
    'Richter',
    'King K. Rool',
    'Isabelle',
    'Incineroar',
    'Pirahna Plant',
    'Joker',
    'Hero',
    'Banjo & Kazooie',
    'Terry',
    'Byleth',
    'Min Min',
    'Mii Brawler',
    'Mii Swordfighter',
    'Mii Gunner',
    'Random',
];

const charCodes = [
    'mario',
    'donkeykong',
    'link',
    'samus',
    'darksamus',
    'yoshi',
    'kirby',
    'fox',
    'pikachu',
    'luigi',
    'ness',
    'captainfalcon',
    'jigglypuff',
    'peach',
    'daisy',
    'bowser',
    'iceclimbers',
    'sheik',
    'zelda',
    'drmario',
    'pichu',
    'falco',
    'marth',
    'lucina',
    'younglink',
    'ganondorf',
    'mewtwo',
    'roy',
    'chrom',
    'mrgameandwatch',
    'metaknight',
    'pit',
    'darkpit',
    'zerosuitsamus',
    'wario',
    'snake',
    'ike',
    'pokemontrainer',
    'diddykong',
    'lucas',
    'sonic',
    'kingdedede',
    'olimar',
    'lucario',
    'rob',
    'toonlink',
    'wolf',
    'villager',
    'megaman',
    'wiifittrainer',
    'rosalinaandluma',
    'littlemac',
    'greninja',
    'palutena',
    'pacman',
    'robin',
    'shulk',
    'bowserjr',
    'duckhunt',
    'ryu',
    'ken',
    'cloud',
    'corrin',
    'bayonetta',
    'inkling',
    'ridley',
    'simon',
    'richter',
    'kingkrool',
    'isabelle',
    'incineroar',
    'pirahnaplant',
    'joker',
    'hero',
    'banjoandkazooie',
    'terry',
    'byleth',
    'minmin',
    'miibrawler',
    'miiswordfighter',
    'miigunner',
    'random',
];

const preset64 = [
    'mario',
    'donkeykong',
    'link',
    'samus',
    'yoshi',
    'kirby',
    'fox',
    'pikachu',
    'luigi',
    'ness',
    'captainfalcon',
    'jigglypuff',
];

const presetMelee = [
    'mario',
    'donkeykong',
    'link',
    'samus',
    'yoshi',
    'kirby',
    'fox',
    'pikachu',
    'luigi',
    'ness',
    'captainfalcon',
    'jigglypuff',
    'peach',
    'bowser',
    'iceclimbers',
    'sheik',
    'zelda',
    'drmario',
    'pichu',
    'falco',
    'marth',
    'younglink',
    'ganondorf',
    'mewtwo',
    'roy',
    'mrgameandwatch',
];

const presetBrawl = [
    'mario',
    'donkeykong',
    'link',
    'samus',
    'yoshi',
    'kirby',
    'fox',
    'pikachu',
    'luigi',
    'ness',
    'captainfalcon',
    'jigglypuff',
    'peach',
    'bowser',
    'iceclimbers',
    'sheik',
    'zelda',
    'falco',
    'marth',
    'ganondorf',
    'mrgameandwatch',
    'metaknight',
    'pit',
    'zerosuitsamus',
    'wario',
    'snake',
    'ike',
    'pokemontrainer',
    'diddykong',
    'lucas',
    'sonic',
    'kingdedede',
    'olimar',
    'lucario',
    'rob',
    'toonlink',
    'wolf',
];

const preset4 = [
    'mario',
    'donkeykong',
    'link',
    'samus',
    'yoshi',
    'kirby',
    'fox',
    'pikachu',
    'luigi',
    'ness',
    'captainfalcon',
    'jigglypuff',
    'peach',
    'bowser',
    'sheik',
    'zelda',
    'drmario',
    'falco',
    'marth',
    'lucina',
    'ganondorf',
    'mewtwo',
    'roy',
    'mrgameandwatch',
    'metaknight',
    'pit',
    'darkpit',
    'zerosuitsamus',
    'wario',
    'ike',
    'pokemontrainer',
    'diddykong',
    'lucas',
    'sonic',
    'kingdedede',
    'olimar',
    'lucario',
    'rob',
    'toonlink',
    'villager',
    'megaman',
    'wiifittrainer',
    'rosalinaandluma',
    'littlemac',
    'greninja',
    'palutena',
    'pacman',
    'robin',
    'shulk',
    'bowserjr.',
    'duckhunt',
    'ryu',
    'cloud',
    'corrin',
    'bayonetta',
];

const presetWeebs = [
    'marth',
    'lucina',
    'roy',
    'chrom',
    'ike',
    'robin',
    'shulk',
    'cloud',
    'corrin',
    'joker',
    'byleth',
];

const presetHeavies = [
    'donkeykong',
    'captainfalcon',
    'bowser',
    'ganondorf',
    'ike',
    'pokemontrainer',
    'kingdedede',
    'wolf',
    'littlemac',
    'ridley',
    'kingkrool',
    'incineroar',
];

const presetSpammers = [
    'link',
    'samus',
    'darksamus',
    'ness',
    'zelda',
    'younglink',
    'snake',
    'rob',
    'toonlink',
    'villager',
    'megaman',
    'wiifittrainer',
    'palutena',
    'pacman',
    'robin',
    'duckhunt',
    'simon',
    'richter',
    'kingkrool'
];
